'use strict';
const assert=require('node:assert/strict');const path=require('node:path');const test=require('node:test');const express=require('express');const request=require('supertest');
const {HiVenuesStore}=require('../src/product/store');const {createHiVenuesPreviewRouter}=require('../src/product/preview-router');const {getMaximalTerritoryHost}=require('../src/product/territory-fixture');const {seedHiVenuesHosts}=require('../src/product/fixtures');
function appFor(store){const app=express();app.set('views',path.join(__dirname,'..','views'));app.set('view engine','ejs');app.use(express.urlencoded({extended:false}));app.use('/hivenues',createHiVenuesPreviewRouter({store}));return app}
function storeFor(host){return new HiVenuesStore({hosts:[structuredClone(host)],now:()=>Date.parse('2026-09-16T05:00:00Z')})}

test('rich v2 public territory exposes semantic multi-surface routes from the live Release',async()=>{const app=appFor(storeFor(getMaximalTerritoryHost()));for(const route of ['/hivenues/lantern-relay/activities','/hivenues/lantern-relay/offers','/hivenues/lantern-relay/stories','/hivenues/lantern-relay/stories/the-roofline-is-an-instrument','/hivenues/lantern-relay/gallery','/hivenues/lantern-relay/people','/hivenues/lantern-relay/people/mara-vale','/hivenues/lantern-relay/about'])await request(app).get(route).expect(200);const stories=await request(app).get('/hivenues/lantern-relay/stories').expect(200);assert.match(stories.text,/cc-territory--poster/);assert.match(stories.text,/The roofline is an instrument/);const profile=await request(app).get('/hivenues/lantern-relay/people/mara-vale').expect(200);assert.match(profile.text,/Fictional program steward/);await request(app).get('/hivenues/lantern-relay/stories/no-such-story').expect(404)});

test('working Preview territory stays on Working while public territory stays on live Release',async()=>{const store=storeFor(getMaximalTerritoryHost());const app=appFor(store);const before=store.snapshot('lantern-relay');const result=store.commit('lantern-relay',before.revision,'territory-preview-story-edit',(draft)=>{draft.stories[0].title='The roofline is an instrument — WORKING CUT';draft.stories[0].body='Working-only territory copy that must never leak into the live Release.'},['stories.story-lantern-roofline-001.title','stories.story-lantern-roofline-001.body'],before.draftDigest);assert.equal(result.ok,true);const preview=await request(app).get('/hivenues/studio/lantern-relay/preview/stories/the-roofline-is-an-instrument').expect(200);assert.match(preview.text,/WORKING CUT/);assert.match(preview.text,/Working-only territory copy/);assert.match(preview.text,/href="\/hivenues\/studio\/lantern-relay\/preview\/people\/mara-vale"/);const live=await request(app).get('/hivenues/lantern-relay/stories/the-roofline-is-an-instrument').expect(200);assert.doesNotMatch(live.text,/WORKING CUT/);assert.doesNotMatch(live.text,/Working-only territory copy/);assert.match(live.text,/This synthetic essay gives the Editorial direction/)});

test('v1 hosts gain only derivable sparse territory routes and fabricate no v2 content',async()=>{const northline=seedHiVenuesHosts().find((host)=>host.identity.slug==='northline-hall');const app=appFor(storeFor(northline));const activities=await request(app).get('/hivenues/northline-hall/activities').expect(200);assert.match(activities.text,/Friday Night Assembly/);await request(app).get('/hivenues/northline-hall/offers').expect(200);await request(app).get('/hivenues/northline-hall/about').expect(200);await request(app).get('/hivenues/northline-hall/stories').expect(404);await request(app).get('/hivenues/northline-hall/gallery').expect(404);await request(app).get('/hivenues/northline-hall/people').expect(404)});

test('same semantic v2 host renders materially different family surface grammars',async()=>{for(const [familyId,marker,heading] of [['poster','cc-territory--poster','Dispatches from the room.'],['editorial','cc-territory--editorial','Field notes'],['hospitality','cc-territory--hospitality','Notes worth carrying home.']]){const host=getMaximalTerritoryHost();host.presentation.compositionFamily=familyId;host.intent.direction=familyId;const response=await request(appFor(storeFor(host))).get('/hivenues/lantern-relay/stories').expect(200);assert.match(response.text,new RegExp(marker));assert.ok(response.text.includes(heading));assert.match(response.text,/The roofline is an instrument/)}});
